/**:
  ros__parameters: 
    rate: 200.0
    x0: 0.0
    y0: 0.0
    theta0: -1.5
    arena_x_length: 5.0
    arena_y_length: 10.0
    obstacles/x: [1.0, -1.0, -2.0]
    obstacles/y: [1.0, -1.0, -2.1]
    obstacles/r: 0.25